/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbaticketsales;

import java.awt.HeadlessException;
import pbaticketsales.MainApplication.AppFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import pbaticketsales.MainApplication.PanelTickets;

/**
 *
 * @author Dewberry
 */
public class LoginFrame extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    
    private int userCount = 0;
    
    ImageIcon login, loginH;
    ImageIcon register, registerH;
    
    
    AppFrame appFrame;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        conn = db.java_db();
        
        //for favicon
        ImageIcon favicon = new ImageIcon(getClass().getResource("/images/login/FAVICON.png"));
        this.setIconImage(favicon.getImage());

        login = new ImageIcon(getClass().getResource("/images/login/LoginBlack.png"));
        loginH = new ImageIcon(getClass().getResource("/images/login/LoginRed.png"));
        register = new ImageIcon(getClass().getResource("/images/login/RegisterBlack.png"));
        registerH = new ImageIcon(getClass().getResource("/images/login/RegisterRed.png"));

        appFrame = new AppFrame();
        
        String sql = "select * from USERS";
        PreparedStatement pst;
        try {
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                userCount++;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldRegPassword = new javax.swing.JPasswordField();
        fieldRegConfirmPassword = new javax.swing.JPasswordField();
        fieldRegUsername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        fieldUsername = new javax.swing.JTextField();
        btnRegister = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PBA Ticket Sales");
        setMinimumSize(new java.awt.Dimension(375, 600));
        setName("PBA Ticket Sales"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(375, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldRegPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldRegPassword.setForeground(new java.awt.Color(255, 255, 255));
        fieldRegPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldRegPassword.setBorder(null);
        fieldRegPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldRegPassword.setOpaque(false);
        fieldRegPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRegPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(fieldRegPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 220, 40));

        fieldRegConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldRegConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        fieldRegConfirmPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldRegConfirmPassword.setBorder(null);
        fieldRegConfirmPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldRegConfirmPassword.setOpaque(false);
        fieldRegConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRegConfirmPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(fieldRegConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 220, 40));

        fieldRegUsername.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        fieldRegUsername.setForeground(new java.awt.Color(255, 255, 255));
        fieldRegUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldRegUsername.setBorder(null);
        fieldRegUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldRegUsername.setOpaque(false);
        fieldRegUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRegUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(fieldRegUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 346, 243, 40));

        fieldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fieldPassword.setForeground(new java.awt.Color(255, 255, 255));
        fieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPassword.setBorder(null);
        fieldPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldPassword.setOpaque(false);
        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 220, 40));

        fieldUsername.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        fieldUsername.setForeground(new java.awt.Color(255, 255, 255));
        fieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldUsername.setBorder(null);
        fieldUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldUsername.setOpaque(false);
        fieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 243, 40));

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login/RegisterBlack.png"))); // NOI18N
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnRegisterMouseReleased(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, -1, 30));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login/LoginBlack.png"))); // NOI18N
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLoginMouseReleased(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login/Background.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 375, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
        checkLogin();
    }//GEN-LAST:event_btnLoginMouseReleased

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setIcon(loginH);
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setIcon(login);
    }//GEN-LAST:event_btnLoginMouseExited

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        checkLogin();
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void fieldRegConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegConfirmPasswordActionPerformed
        checkRegister();
    }//GEN-LAST:event_fieldRegConfirmPasswordActionPerformed

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        btnRegister.setIcon(registerH);
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        btnRegister.setIcon(register);
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnRegisterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseReleased
        checkRegister();
    }//GEN-LAST:event_btnRegisterMouseReleased

    private void fieldRegPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegPasswordActionPerformed
        checkRegister();
    }//GEN-LAST:event_fieldRegPasswordActionPerformed

    private void fieldRegUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegUsernameActionPerformed
        checkRegister();
    }//GEN-LAST:event_fieldRegUsernameActionPerformed

    private void fieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsernameActionPerformed
        checkLogin();
    }//GEN-LAST:event_fieldUsernameActionPerformed

    private void checkLogin(){
        String sql = "select * from Users where(username =? and password=?)";
        PreparedStatement pst;
        
        try {
            int count = 0;
            pst = conn.prepareStatement(sql);
            pst.setString(1, fieldUsername.getText());
            pst.setString(2, String.valueOf(fieldPassword.getPassword()));
            
            rs = pst.executeQuery();
            while (rs.next()){
                //setUser Details
                setUser(rs);
                
                count++;
            }
            
            if (count == 1){
                JOptionPane.showMessageDialog(this, "Success!");
                
                //if a cash is 0, then add some money
                if (AppFrame.currentLoggedCash <= 0){
                   appFrame.setVisible(true);
                } 
                //else, show start transaction without adding money
                else {
                    appFrame.setVisible(true);
                    appFrame.showTickets();
                }
                
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(this, "Invalid username or password");
            }
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void checkRegister(){
        String sql = "insert into Users VALUES (?,?,?,?,?)";
        PreparedStatement pst;
        
        //if password and confirm password is match
        if (fieldRegPassword.getText().equals(fieldRegConfirmPassword.getText())){
            
            try {
                    pst = conn.prepareStatement(sql);
                    pst.setInt(1, userCount+1);
                    pst.setString(2, fieldRegUsername.getText());
                    pst.setString(3, String.valueOf(fieldRegPassword.getPassword()));
                    pst.setInt(4, 0);
                    pst.setString(5, "");

                    //if username and password is not blank, then register user
                    if (fieldRegUsername.getText().trim().equals("") == false && fieldRegPassword.getText().trim().equals("") == false){
                        pst.executeUpdate();

                        userCount += 1;
                        JOptionPane.showMessageDialog(this, "Success! You may now proceed to login.");
                        
                        fieldRegUsername.setText("");
                        fieldRegConfirmPassword.setText("");
                        fieldRegPassword.setText("");
                        fieldUsername.requestFocus();
                        
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Username or Password can't be blank.");
                    }
                        
                    
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Username already exists. Please try another username.");
            }
        }
        
        //else
        else {
                JOptionPane.showMessageDialog(this, "Entered Password didn't match.");
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPasswordField fieldRegConfirmPassword;
    private javax.swing.JPasswordField fieldRegPassword;
    private javax.swing.JTextField fieldRegUsername;
    private javax.swing.JTextField fieldUsername;
    // End of variables declaration//GEN-END:variables

    private void setUser(ResultSet rs) throws SQLException {
        AppFrame.currentLoggedID = rs.getInt("id");
        
        AppFrame.currentLoggedUserName = rs.getString("username");
        AppFrame.currentLoggedCash = rs.getInt("cash");
        
    }
}
