/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pbaticketsales.MainApplication;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import pbaticketsales.MainApplication.PanelTickets;
import pbaticketsales.db;

/**
 *
 * @author Dewberry
 */
public class AppFrame extends javax.swing.JFrame {
    ImageIcon iconTicketPrices, iconTicketPricesH,iconStartTransaction,iconStartTransactionH;
    
    Connection conn = null;
    
    public static int currentLoggedID = 0;
    public static String currentLoggedUserName = "User";
    public static double currentLoggedCash = 0;
    
    
    //windows
    public static CardLayout cardLayout;
    PanelTickets panelTickets;
    PanelSeats panelSeats;
    PanelCalculator panelCalculator;
    PanelReceipt panelReceipt;
    FramePrices framePrices;
    
    /** Creates new form AppFrame */
    public AppFrame() {
        initComponents();
        conn = db.java_db();
        
        //for favicon
        ImageIcon favicon = new ImageIcon(getClass().getResource("/images/login/FAVICON.png"));
        this.setIconImage(favicon.getImage());
        
        //loads the images
        iconTicketPrices = new ImageIcon(getClass().getResource("/images/homescreen/TicketBlack.png"));
        iconTicketPricesH = new ImageIcon(getClass().getResource("/images/homescreen/TicketRed.png"));
        iconStartTransaction = new ImageIcon(getClass().getResource("/images/homescreen/StartTranBlack.png"));
        iconStartTransactionH = new ImageIcon(getClass().getResource("/images/homescreen/StartTranRed.png"));
        
        //panels
        panelTickets = new PanelTickets();
        panelSeats = new PanelSeats();
        panelCalculator = new PanelCalculator();
        panelReceipt = new PanelReceipt();
        cardLayout = (CardLayout)getContentPane().getLayout();
        add(panelTickets, "cardTickets");
        add(panelSeats, "cardSeats");
        add(panelCalculator, "cardCalculator");
        add(panelReceipt, "cardReceipt");
        
        framePrices = new FramePrices();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWelcome = new javax.swing.JPanel();
        btnStartTransaction = new javax.swing.JLabel();
        btnTicketPrices = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        fieldCash = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PBA TICKET SALES");
        setResizable(false);
        setSize(new java.awt.Dimension(375, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        panelWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStartTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homescreen/StartTranBlack.png"))); // NOI18N
        btnStartTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStartTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStartTransactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStartTransactionMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStartTransactionMouseReleased(evt);
            }
        });
        panelWelcome.add(btnStartTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 60));

        btnTicketPrices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homescreen/TicketBlack.png"))); // NOI18N
        btnTicketPrices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTicketPrices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTicketPricesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTicketPricesMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTicketPricesMouseReleased(evt);
            }
        });
        panelWelcome.add(btnTicketPrices, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 60));

        lblName.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 204, 204));
        lblName.setText("User");
        panelWelcome.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        fieldCash.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        fieldCash.setForeground(new java.awt.Color(255, 255, 255));
        fieldCash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldCash.setText("1000");
        fieldCash.setBorder(null);
        fieldCash.setCaretColor(new java.awt.Color(255, 255, 255));
        fieldCash.setOpaque(false);
        panelWelcome.add(fieldCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 220, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homescreen/Background.png"))); // NOI18N
        panelWelcome.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelWelcome, "cardTransaction");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTicketPricesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketPricesMouseEntered
        btnTicketPrices.setIcon(iconTicketPricesH);
    }//GEN-LAST:event_btnTicketPricesMouseEntered

    private void btnTicketPricesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketPricesMouseExited
        btnTicketPrices.setIcon(iconTicketPrices);
    }//GEN-LAST:event_btnTicketPricesMouseExited

    private void btnTicketPricesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTicketPricesMouseReleased
        framePrices.setVisible(true);
    }//GEN-LAST:event_btnTicketPricesMouseReleased

    private void btnStartTransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartTransactionMouseEntered
        btnStartTransaction.setIcon(iconStartTransactionH);
    }//GEN-LAST:event_btnStartTransactionMouseEntered

    private void btnStartTransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartTransactionMouseExited
        btnStartTransaction.setIcon(iconStartTransaction);
    }//GEN-LAST:event_btnStartTransactionMouseExited

    private void btnStartTransactionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartTransactionMouseReleased
        PreparedStatement pst;
        String sql = "update Users set cash = ? where id =?";
        
        try {
            
            pst = conn.prepareStatement(sql);
            pst.setDouble(1, Double.parseDouble(fieldCash.getText()));
            pst.setInt(2, currentLoggedID);
            pst.executeUpdate();
            
            //updates user cash
            currentLoggedCash += Double.parseDouble(fieldCash.getText());
            
            //go to next frame
            cardLayout.show(getContentPane(), "cardTickets");
            
        } catch (SQLException ex) {
            Logger.getLogger(AppFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStartTransactionMouseReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //sets the Last name and User ID
        lblName.setText(currentLoggedUserName.toUpperCase());
    }//GEN-LAST:event_formComponentShown
    
    public void showTickets(){
        cardLayout.show(getContentPane(), "cardTickets");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnStartTransaction;
    private javax.swing.JLabel btnTicketPrices;
    private javax.swing.JTextField fieldCash;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel panelWelcome;
    // End of variables declaration//GEN-END:variables

}
