/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbaticketsales.MainApplication;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Dewberry
 */
public class FrameReceipt extends javax.swing.JFrame {
    private int count = 0;
    
    /**
     * Creates new form FrameReceipt
     */
    public FrameReceipt() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lblInfo = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(10, 10));
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N

        lblInfo.setEditable(false);
        lblInfo.setColumns(20);
        lblInfo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblInfo.setLineWrap(true);
        lblInfo.setRows(5);
        lblInfo.setText("-------------PBA TICKET SALES-------------\n          ANGELES CITY, PAMPANGA\n       OPERATED BY: ATLAS (GROUP 1)\n                         \n               USER ID: -1\n \n                -RECEIPT-\n\n   USER INFO:\n   *USERNAME*     CASH DEPOSITED: 3000\n   03/25/17\n               \n   ORDER DESCRIPTION           PRICE\n  --------------------------------------\n   GENERAL ADMISSION           250\n   LOWER BOX                   350\n   UPPER BOX                   350\n   COURTSIDE                   500\n\n\n   DISCOUNTS\n  --------------------------------------\n   TYPE                        STUDENT\n   PERCENT                     .25\n   DISCOUNT PRICE              350\n\n   TRANSACTION\n  -------------------------------------\n   CASH                        3000\n   TOTAL PRICE                 500\n  \n\n   CHANGE:                     2500\n\n   --------------------------------\n           OFFICIAL RECEIPT\n         BY GROUP 1: 11-ATLAS\n        THANK YOU! COME AGAIN.");
        lblInfo.setToolTipText("");
        lblInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jScrollPane1.setViewportView(lblInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 347, 670));

        btnPrint.setBackground(new java.awt.Color(255, 255, 255));
        btnPrint.setFont(new java.awt.Font("Futura Bk BT", 0, 12)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(102, 102, 102));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 347, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        lblInfo.setText("");
        
        Timer timer = new Timer();
        
        timer.schedule(new TimerTask(){
            @Override
            public void run() {
                updateReceipt();
                count++;
                
                
                if (count == 32) {
                    this.cancel();
                }
            }
        }, 0, 1 * 100);
    }//GEN-LAST:event_formComponentShown

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void updateReceipt(){
        
        
        String pastInfo = lblInfo.getText();
        
        //for date
        
        String currentDate = PanelReceipt.currentDate;

       
        if (count == 0)
            lblInfo.setText(pastInfo + "-------------PBA TICKET SALES-------------\n");
        if (count == 1)
            lblInfo.setText(pastInfo + "          ANGELES CITY, PAMPANGA\n");
        if (count == 2)
            lblInfo.setText(pastInfo + "       OPERATED BY: ATLAS (GROUP 1)\n");
        if (count == 3)
            lblInfo.setText(pastInfo + "\n");
        if (count == 4)
            lblInfo.setText(pastInfo + "               USER ID: " + AppFrame.currentLoggedID + "\n");
        if (count == 5)
            lblInfo.setText(pastInfo + "                -RECEIPT-\n");
        if (count == 6)
            lblInfo.setText(pastInfo + "\n");
        if (count == 7)
            lblInfo.setText(pastInfo + "   USER INFO:\n");
        if (count == 8)
            lblInfo.setText(pastInfo + "   " + AppFrame.currentLoggedUserName + "     CASH DEPOSITED: " + AppFrame.currentLoggedCash+ "\n");
        if (count == 9)
            lblInfo.setText(pastInfo + "   "+ currentDate +"\n");
        if (count == 10)
            lblInfo.setText(pastInfo + "\n");
        if (count == 11)
            lblInfo.setText(pastInfo + "   ORDER DESCRIPTION           PRICE\n");
        if (count == 12)
            lblInfo.setText(pastInfo + "  --------------------------------------\n");
        if (count == 13) {
            if (PanelTickets.ticketChosed == 1)
                lblInfo.setText(pastInfo + "   TALK-N-TEXT vs GLOBALPORT   \n");
            if (PanelTickets.ticketChosed == 2)
                lblInfo.setText(pastInfo + "   SAN MIGUEL vs KIA SORENTO   \n");
            if (PanelTickets.ticketChosed == 3)
                lblInfo.setText(pastInfo + "   MERALCO vs ALASKA           \n");
            if (PanelTickets.ticketChosed == 4)
                lblInfo.setText(pastInfo + "   PHOENIX vs NLEX             \n");
        }          
        if (count == 14)
            if (PanelSeats.seatChosed == "GENERAL ADMISSION")
                lblInfo.setText(pastInfo + "   " + PanelSeats.seatChosed  + "           " + PanelSeats.totalPayment +"\n");
            else 
                lblInfo.setText(pastInfo + "   " + PanelSeats.seatChosed  + "                   " + PanelSeats.totalPayment +"\n");
        if (count == 15)
            lblInfo.setText(pastInfo + "\n");
        if (count == 16)
            lblInfo.setText(pastInfo + "    DISCOUNTS\n");
        if (count == 17)
            lblInfo.setText(pastInfo + "  --------------------------------------\n");
        if (count == 18)
            lblInfo.setText(pastInfo + "   PERCENT                     " + PromptDiscount.totalDiscount + "\n");
        if (count == 19)
            lblInfo.setText(pastInfo + "   DISCOUNT PRICE              " + PanelReceipt.discountPrice + "\n" );
        if (count == 20)
            lblInfo.setText(pastInfo + "\n");
        if (count == 21)
            lblInfo.setText(pastInfo + "   TRANSACTION\n");
        if (count == 22)
            lblInfo.setText(pastInfo + "  -------------------------------------\n");
        if (count == 23)
            lblInfo.setText(pastInfo + "   CASH                        " + AppFrame.currentLoggedCash +"\n");
        if (count == 24)
            lblInfo.setText(pastInfo + "   TOTAL PRICE                 " + PanelReceipt.totalPrice + "\n");
        if (count == 25)
            lblInfo.setText(pastInfo + "\n");
        if (count == 26)
            lblInfo.setText(pastInfo + "\n");
        if (count == 27)
            lblInfo.setText(pastInfo + "   CHANGE:                     "+ PanelReceipt.change +"\n");
        if (count == 28)
            lblInfo.setText(pastInfo + "\n");
        if (count == 29)
            lblInfo.setText(pastInfo + "   --------------------------------\n");
        if (count == 30)
            lblInfo.setText(pastInfo + "           OFFICIAL RECEIPT\n");
        if (count == 31)
            lblInfo.setText(pastInfo + "         BY GROUP 1: 11-ATLAS\n");
        if (count == 32)
            lblInfo.setText(pastInfo + "        THANK YOU! COME AGAIN.   \n");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblInfo;
    // End of variables declaration//GEN-END:variables
}
