package pbaticketsales.MainApplication;


import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import pbaticketsales.LoginFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dewberry
 */
public class PanelTickets extends javax.swing.JPanel {
    ImageIcon iconChoice1, iconChoice1h;
    ImageIcon iconChoice2, iconChoice2h;
    ImageIcon iconChoice3, iconChoice3h;
    ImageIcon iconChoice4, iconChoice4h;
    
    public static int ticketChosed;
    
    /**
     * Creates new form PanelTickets
     */
    public PanelTickets() {
        initComponents();
        iconChoice1 = new ImageIcon(getClass().getResource("/images/tickets/TNTVSGPblack.png"));
        iconChoice1h = new ImageIcon(getClass().getResource("/images/tickets/TNTVSGPred.png"));
        iconChoice2 = new ImageIcon(getClass().getResource("/images/tickets/SANMIGVSKIAblack.png"));
        iconChoice2h = new ImageIcon(getClass().getResource("/images/tickets/SANMIGVSKIAred.png"));
        iconChoice3 = new ImageIcon(getClass().getResource("/images/tickets/MERVSALASblack.png"));
        iconChoice3h = new ImageIcon(getClass().getResource("/images/tickets/MERVSALASred.png"));
        iconChoice4 = new ImageIcon(getClass().getResource("/images/tickets/PHOEVSNLEXblack.png"));
        iconChoice4h = new ImageIcon(getClass().getResource("/images/tickets/PHOEVSNLEXred.png"));
        
        loadHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nav = new javax.swing.JPanel();
        dropDown = new javax.swing.JLabel();
        accountTab = new javax.swing.JLabel();
        calculatorTab = new javax.swing.JLabel();
        seatsTab = new javax.swing.JLabel();
        ticketsTab = new javax.swing.JLabel();
        lblCash = new javax.swing.JLabel();
        choice4 = new javax.swing.JLabel();
        choice3 = new javax.swing.JLabel();
        choice2 = new javax.swing.JLabel();
        choice1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setOpaque(false);
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dropdown/DropDown.png"))); // NOI18N
        dropDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav.add(dropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 38, -1, -1));

        accountTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dropdown/AccountBtnGray.png"))); // NOI18N
        accountTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav.add(accountTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        calculatorTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator/CalculatorBtnGray.png"))); // NOI18N
        nav.add(calculatorTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        seatsTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/SeatsBtnGray.png"))); // NOI18N
        nav.add(seatsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        ticketsTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/TICKETBTNred.png"))); // NOI18N
        nav.add(ticketsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 270, 90));

        lblCash.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblCash.setForeground(new java.awt.Color(204, 204, 204));
        lblCash.setText("0");
        add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 578, 80, 20));

        choice4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/PHOEVSNLEXblack.png"))); // NOI18N
        choice4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choice4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choice4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choice4MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                choice4MouseReleased(evt);
            }
        });
        add(choice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        choice3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/MERVSALASblack.png"))); // NOI18N
        choice3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choice3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choice3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choice3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                choice3MouseReleased(evt);
            }
        });
        add(choice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        choice2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/SANMIGVSKIAblack.png"))); // NOI18N
        choice2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choice2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choice2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choice2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                choice2MouseReleased(evt);
            }
        });
        add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        choice1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/TNTVSGPblack.png"))); // NOI18N
        choice1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                choice1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                choice1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                choice1MouseReleased(evt);
            }
        });
        add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/Background.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void choice4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice4MouseEntered
        choice4.setIcon(iconChoice4h);
    }//GEN-LAST:event_choice4MouseEntered

    private void choice4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice4MouseExited
        choice4.setIcon(iconChoice4);
    }//GEN-LAST:event_choice4MouseExited

    private void choice3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice3MouseEntered
        choice3.setIcon(iconChoice3h);
    }//GEN-LAST:event_choice3MouseEntered

    private void choice3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice3MouseExited
        choice3.setIcon(iconChoice3);
    }//GEN-LAST:event_choice3MouseExited

    private void choice2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice2MouseEntered
        choice2.setIcon(iconChoice2h);
    }//GEN-LAST:event_choice2MouseEntered

    private void choice2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice2MouseExited
        choice2.setIcon(iconChoice2);
    }//GEN-LAST:event_choice2MouseExited

    private void choice1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice1MouseEntered
        choice1.setIcon(iconChoice1h);
    }//GEN-LAST:event_choice1MouseEntered

    private void choice1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice1MouseExited
        choice1.setIcon(iconChoice1);
    }//GEN-LAST:event_choice1MouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //updates the cash everytime the component is shown
        lblCash.setText(String.valueOf(AppFrame.currentLoggedCash));
    }//GEN-LAST:event_formComponentShown

    private void choice1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice1MouseReleased
        
        ticketChosed = 1;
        AppFrame.cardLayout.show(this.getParent(), "cardSeats");
    }//GEN-LAST:event_choice1MouseReleased

    private void choice2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice2MouseReleased
        
        ticketChosed = 2;
        AppFrame.cardLayout.show(this.getParent(), "cardSeats");
    }//GEN-LAST:event_choice2MouseReleased

    private void choice3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice3MouseReleased
        
        ticketChosed = 3;
        AppFrame.cardLayout.show(this.getParent(), "cardSeats");
    }//GEN-LAST:event_choice3MouseReleased

    private void choice4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice4MouseReleased
        
        ticketChosed = 4;
        AppFrame.cardLayout.show(this.getParent(), "cardSeats");
    }//GEN-LAST:event_choice4MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountTab;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel calculatorTab;
    private javax.swing.JLabel choice1;
    private javax.swing.JLabel choice2;
    private javax.swing.JLabel choice3;
    private javax.swing.JLabel choice4;
    private javax.swing.JLabel dropDown;
    private javax.swing.JLabel lblCash;
    private javax.swing.JPanel nav;
    private javax.swing.JLabel seatsTab;
    private javax.swing.JLabel ticketsTab;
    // End of variables declaration//GEN-END:variables

    private void loadHeader() {
        
        dropDown.setVisible(false);
        
        accountTab.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ImageIcon accountHovered = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnRed.png"));
                accountTab.setIcon(accountHovered);
            }
            @Override
            public void mouseExited(MouseEvent e) {
                ImageIcon accountExited = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnGray.png"));
                if (!dropDown.isVisible())
                    accountTab.setIcon(accountExited);
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                ImageIcon accountHovered = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnRed.png"));
                accountTab.setIcon(accountHovered);
                
                if (!dropDown.isVisible())
                    dropDown.setVisible(true);
                else
                    dropDown.setVisible(false);
            }
            
        });
        
        dropDown.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ImageIcon dropHistoryHovered = new ImageIcon(getClass().getResource("/images/dropdown/DropDownHistorySelect.png"));
                ImageIcon dropLogoutHovered = new ImageIcon(getClass().getResource("/images/dropdown/DropDownLogoutSelect.png"));
                
                dropDown.addMouseMotionListener(new MouseMotionAdapter() {
                    @Override
                    public void mouseMoved(MouseEvent e) {
                        if (e.getY() < 20){
                            dropDown.setIcon(dropHistoryHovered);
                        } else {
                            dropDown.setIcon(dropLogoutHovered);
                        }
                    }
                
                    
                });
                
            }
            @Override
            public void mouseExited(MouseEvent e) {
                
                ImageIcon dropExited = new ImageIcon(getClass().getResource("/images/dropdown/DropDown.png"));
                dropDown.setIcon(dropExited);
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.getY() < 20){
                    FrameHistory frameHistory = new FrameHistory();
                    
                    frameHistory.setVisible(true);
                } else {
                    LoginFrame loginFrame = new LoginFrame();
                    loginFrame.setVisible(true);
                    
                    JFrame thisFrame = (JFrame)SwingUtilities.getWindowAncestor(getComponent(0));
                    thisFrame.dispose();
                    
                }
                
                dropDown.setVisible(false);
            }
            
        });
        
    }
}
