/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbaticketsales.MainApplication;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import pbaticketsales.LoginFrame;

/**
 *
 * @author Dewberry
 */
public class PanelCalculator extends javax.swing.JPanel {
    double num1, num2;
    String operation;
    /**
     * Creates new form PanelCalculator
     */
    public PanelCalculator() {
        initComponents();
        
        loadHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nav = new javax.swing.JPanel();
        dropDown = new javax.swing.JLabel();
        accountTab = new javax.swing.JLabel();
        calculatorTab = new javax.swing.JLabel();
        seatsTab = new javax.swing.JLabel();
        ticketsTab = new javax.swing.JLabel();
        field = new javax.swing.JTextField();
        btnDot = new javax.swing.JPanel();
        btnEquals = new javax.swing.JPanel();
        btnPlus = new javax.swing.JPanel();
        btnMinus = new javax.swing.JPanel();
        btnMutiply = new javax.swing.JPanel();
        btnDivide = new javax.swing.JPanel();
        btnPercent = new javax.swing.JPanel();
        btnNegative = new javax.swing.JPanel();
        btnC = new javax.swing.JPanel();
        btn9 = new javax.swing.JPanel();
        btn8 = new javax.swing.JPanel();
        btn7 = new javax.swing.JPanel();
        btn6 = new javax.swing.JPanel();
        btn5 = new javax.swing.JPanel();
        btn3 = new javax.swing.JPanel();
        btn2 = new javax.swing.JPanel();
        btn0 = new javax.swing.JPanel();
        btn4 = new javax.swing.JPanel();
        btn1 = new javax.swing.JPanel();
        bgCalculator = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setOpaque(false);
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dropdown/DropDown.png"))); // NOI18N
        dropDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav.add(dropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 38, -1, -1));

        accountTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dropdown/AccountBtnGray.png"))); // NOI18N
        accountTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav.add(accountTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        calculatorTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator/CalculatorBtnRed.png"))); // NOI18N
        nav.add(calculatorTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        seatsTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/SeatsBtnGray.png"))); // NOI18N
        nav.add(seatsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        ticketsTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/TICKETBTNgray.png"))); // NOI18N
        nav.add(ticketsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 270, 90));

        field.setEditable(false);
        field.setBackground(new java.awt.Color(51, 51, 51));
        field.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        field.setForeground(new java.awt.Color(255, 255, 255));
        field.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        field.setBorder(null);
        field.setMargin(new java.awt.Insets(2, 20, 2, 20));
        field.setOpaque(false);
        add(field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 100));

        btnDot.setOpaque(false);
        btnDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDotMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnDotLayout = new javax.swing.GroupLayout(btnDot);
        btnDot.setLayout(btnDotLayout);
        btnDotLayout.setHorizontalGroup(
            btnDotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnDotLayout.setVerticalGroup(
            btnDotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        add(btnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 90, 90));

        btnEquals.setOpaque(false);
        btnEquals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEqualsMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnEqualsLayout = new javax.swing.GroupLayout(btnEquals);
        btnEquals.setLayout(btnEqualsLayout);
        btnEqualsLayout.setHorizontalGroup(
            btnEqualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnEqualsLayout.setVerticalGroup(
            btnEqualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 90, 80));

        btnPlus.setOpaque(false);
        btnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlusMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnPlusLayout = new javax.swing.GroupLayout(btnPlus);
        btnPlus.setLayout(btnPlusLayout);
        btnPlusLayout.setHorizontalGroup(
            btnPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnPlusLayout.setVerticalGroup(
            btnPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 90, 80));

        btnMinus.setOpaque(false);
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMinusMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnMinusLayout = new javax.swing.GroupLayout(btnMinus);
        btnMinus.setLayout(btnMinusLayout);
        btnMinusLayout.setHorizontalGroup(
            btnMinusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnMinusLayout.setVerticalGroup(
            btnMinusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 90, 80));

        btnMutiply.setOpaque(false);
        btnMutiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMutiplyMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnMutiplyLayout = new javax.swing.GroupLayout(btnMutiply);
        btnMutiply.setLayout(btnMutiplyLayout);
        btnMutiplyLayout.setHorizontalGroup(
            btnMutiplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnMutiplyLayout.setVerticalGroup(
            btnMutiplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btnMutiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 90, 80));

        btnDivide.setOpaque(false);
        btnDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDivideMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnDivideLayout = new javax.swing.GroupLayout(btnDivide);
        btnDivide.setLayout(btnDivideLayout);
        btnDivideLayout.setHorizontalGroup(
            btnDivideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnDivideLayout.setVerticalGroup(
            btnDivideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, 80));

        btnPercent.setOpaque(false);
        btnPercent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPercentMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnPercentLayout = new javax.swing.GroupLayout(btnPercent);
        btnPercent.setLayout(btnPercentLayout);
        btnPercentLayout.setHorizontalGroup(
            btnPercentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnPercentLayout.setVerticalGroup(
            btnPercentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btnPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 90, 80));

        btnNegative.setOpaque(false);
        btnNegative.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnNegativeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnNegativeLayout = new javax.swing.GroupLayout(btnNegative);
        btnNegative.setLayout(btnNegativeLayout);
        btnNegativeLayout.setHorizontalGroup(
            btnNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnNegativeLayout.setVerticalGroup(
            btnNegativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btnNegative, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 90, 80));

        btnC.setOpaque(false);
        btnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnCLayout = new javax.swing.GroupLayout(btnC);
        btnC.setLayout(btnCLayout);
        btnCLayout.setHorizontalGroup(
            btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btnCLayout.setVerticalGroup(
            btnCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 90, 80));

        btn9.setOpaque(false);
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn9MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn9Layout = new javax.swing.GroupLayout(btn9);
        btn9.setLayout(btn9Layout);
        btn9Layout.setHorizontalGroup(
            btn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btn9Layout.setVerticalGroup(
            btn9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 90, 80));

        btn8.setOpaque(false);
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn8MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn8Layout = new javax.swing.GroupLayout(btn8);
        btn8.setLayout(btn8Layout);
        btn8Layout.setHorizontalGroup(
            btn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btn8Layout.setVerticalGroup(
            btn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 90, 80));

        btn7.setOpaque(false);
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn7MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn7Layout = new javax.swing.GroupLayout(btn7);
        btn7.setLayout(btn7Layout);
        btn7Layout.setHorizontalGroup(
            btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btn7Layout.setVerticalGroup(
            btn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 90, 80));

        btn6.setOpaque(false);
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn6Layout = new javax.swing.GroupLayout(btn6);
        btn6.setLayout(btn6Layout);
        btn6Layout.setHorizontalGroup(
            btn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btn6Layout.setVerticalGroup(
            btn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 90, 80));

        btn5.setOpaque(false);
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn5Layout = new javax.swing.GroupLayout(btn5);
        btn5.setLayout(btn5Layout);
        btn5Layout.setHorizontalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btn5Layout.setVerticalGroup(
            btn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 100, 90));

        btn3.setOpaque(false);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn3Layout = new javax.swing.GroupLayout(btn3);
        btn3.setLayout(btn3Layout);
        btn3Layout.setHorizontalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btn3Layout.setVerticalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 90, 80));

        btn2.setOpaque(false);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn2Layout = new javax.swing.GroupLayout(btn2);
        btn2.setLayout(btn2Layout);
        btn2Layout.setHorizontalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btn2Layout.setVerticalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 100, 90));

        btn0.setOpaque(false);
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn0MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn0Layout = new javax.swing.GroupLayout(btn0);
        btn0.setLayout(btn0Layout);
        btn0Layout.setHorizontalGroup(
            btn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        btn0Layout.setVerticalGroup(
            btn0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 190, 90));

        btn4.setOpaque(false);
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn4Layout = new javax.swing.GroupLayout(btn4);
        btn4.setLayout(btn4Layout);
        btn4Layout.setHorizontalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btn4Layout.setVerticalGroup(
            btn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 90, 80));

        btn1.setOpaque(false);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn1Layout = new javax.swing.GroupLayout(btn1);
        btn1.setLayout(btn1Layout);
        btn1Layout.setHorizontalGroup(
            btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        btn1Layout.setVerticalGroup(
            btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 90, 90));

        bgCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator/Background.png"))); // NOI18N
        add(bgCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseReleased
        field.setText(field.getText() + ".");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDotMouseReleased

    private void btnEqualsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualsMouseReleased
        double result = 0;
        num2 = Double.parseDouble (field.getText());

        if (operation == "divide") {
            result = num1 / num2;
        }

        else if (operation == "multiply"){
            result = num1 * num2;
        }

        else if (operation == "addition"){
            result = num1 + num2;

        }

        else if (operation == "subtraction"){
            result = num1 - num2;
        }

        field.setText(String.valueOf(result) );

    }//GEN-LAST:event_btnEqualsMouseReleased

    private void btnPlusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMouseReleased
        num1 =Double.parseDouble (field.getText());
        field.setText("");

        operation = "addition";        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusMouseReleased

    private void btnMinusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseReleased
        num1 =Double.parseDouble (field.getText());
        field.setText("");

        operation = "subtraction";        // TODO add your handling code here:
    }//GEN-LAST:event_btnMinusMouseReleased

    private void btnMutiplyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMutiplyMouseReleased
        num1 =Double.parseDouble (field.getText());
        field.setText("");

        operation = "multiply";

        // TODO add your handling code here:
    }//GEN-LAST:event_btnMutiplyMouseReleased

    private void btnDivideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMouseReleased

        num1 =Double.parseDouble (field.getText());
        field.setText("");

        operation = "divide";

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivideMouseReleased

    private void btnPercentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPercentMouseReleased
        double number = Double.parseDouble(field.getText());
        number = number / 100;

        field.setText(String.valueOf(number));

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPercentMouseReleased

    private void btnNegativeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNegativeMouseReleased
        double number = Double.parseDouble(field.getText());

        number = number * -1;
        field.setText(String.valueOf(number));
    }//GEN-LAST:event_btnNegativeMouseReleased

    private void btnCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCMouseReleased
        String number = field.getText();

        if (number.equals("") == false){
            number = number.substring(0, number.length() - 1);
        }

        field.setText(number);

    }//GEN-LAST:event_btnCMouseReleased

    private void btn9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseReleased
        field.setText(field.getText() + "9");        // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseReleased

    private void btn8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseReleased
        field.setText(field.getText() + "8");        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseReleased

    private void btn7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseReleased
        field.setText(field.getText() + "7");        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseReleased

    private void btn6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseReleased
        field.setText(field.getText() + "6");        // TODO add your handling code here:
    }//GEN-LAST:event_btn6MouseReleased

    private void btn5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseReleased
        field.setText(field.getText() + "5"); // TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseReleased

    private void btn3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseReleased
        field.setText(field.getText() + "3");        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseReleased

    private void btn2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseReleased
        field.setText(field.getText() + "2");        // TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseReleased

    private void btn0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseReleased
        field.setText(field.getText() + "0");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn0MouseReleased

    private void btn4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseReleased
        field.setText(field.getText() + "4");        // TODO add your handling code here:
    }//GEN-LAST:event_btn4MouseReleased

    private void btn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseReleased
        field.setText(field.getText() + "1");                  // TODO add your handling code here:
    }//GEN-LAST:event_btn1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountTab;
    private javax.swing.JLabel bgCalculator;
    private javax.swing.JPanel btn0;
    private javax.swing.JPanel btn1;
    private javax.swing.JPanel btn2;
    private javax.swing.JPanel btn3;
    private javax.swing.JPanel btn4;
    private javax.swing.JPanel btn5;
    private javax.swing.JPanel btn6;
    private javax.swing.JPanel btn7;
    private javax.swing.JPanel btn8;
    private javax.swing.JPanel btn9;
    private javax.swing.JPanel btnC;
    private javax.swing.JPanel btnDivide;
    private javax.swing.JPanel btnDot;
    private javax.swing.JPanel btnEquals;
    private javax.swing.JPanel btnMinus;
    private javax.swing.JPanel btnMutiply;
    private javax.swing.JPanel btnNegative;
    private javax.swing.JPanel btnPercent;
    private javax.swing.JPanel btnPlus;
    private javax.swing.JLabel calculatorTab;
    private javax.swing.JLabel dropDown;
    private javax.swing.JTextField field;
    private javax.swing.JPanel nav;
    private javax.swing.JLabel seatsTab;
    private javax.swing.JLabel ticketsTab;
    // End of variables declaration//GEN-END:variables
    private void loadHeader() {
        
        dropDown.setVisible(false);
        
        accountTab.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ImageIcon accountHovered = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnRed.png"));
                accountTab.setIcon(accountHovered);
            }
            @Override
            public void mouseExited(MouseEvent e) {
                ImageIcon accountExited = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnGray.png"));
                if (!dropDown.isVisible())
                    accountTab.setIcon(accountExited);
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                ImageIcon accountHovered = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnRed.png"));
                accountTab.setIcon(accountHovered);
                
                if (!dropDown.isVisible())
                    dropDown.setVisible(true);
                else
                    dropDown.setVisible(false);
            }
            
        });
        
        dropDown.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ImageIcon dropHistoryHovered = new ImageIcon(getClass().getResource("/images/dropdown/DropDownHistorySelect.png"));
                ImageIcon dropLogoutHovered = new ImageIcon(getClass().getResource("/images/dropdown/DropDownLogoutSelect.png"));
                
                dropDown.addMouseMotionListener(new MouseMotionAdapter() {
                    @Override
                    public void mouseMoved(MouseEvent e) {
                        if (e.getY() < 20){
                            dropDown.setIcon(dropHistoryHovered);
                        } else {
                            dropDown.setIcon(dropLogoutHovered);
                        }
                    }
                
                    
                });
                
            }
            @Override
            public void mouseExited(MouseEvent e) {
                
                ImageIcon dropExited = new ImageIcon(getClass().getResource("/images/dropdown/DropDown.png"));
                dropDown.setIcon(dropExited);
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.getY() < 20){
                    FrameHistory frameHistory = new FrameHistory();
                    
                    frameHistory.setVisible(true);
                } else {
                    LoginFrame loginFrame = new LoginFrame();
                    loginFrame.setVisible(true);
                    
                    JFrame thisFrame = (JFrame)SwingUtilities.getWindowAncestor(getComponent(0));
                    thisFrame.dispose();
                    
                }
                
                dropDown.setVisible(false);
            }
            
        });
        
    }

}
