package pbaticketsales.MainApplication;


import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import pbaticketsales.LoginFrame;
import static pbaticketsales.MainApplication.PromptDiscount.isDiscountAlreadySelected;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dewberry
 */
public class PanelSeats extends javax.swing.JPanel {
    ImageIcon iconContinue, iconContinueH;
    PromptDiscount prompt;
    public static double totalPayment;
    
    public static String seatChosed = "none";
    
    /**
     * Creates new form PanelTickets
     */
    public PanelSeats() {
        initComponents();
        iconContinue = new ImageIcon(getClass().getResource("/images/seats/ContinueBlack.png"));
        iconContinueH = new ImageIcon(getClass().getResource("/images/seats/ContinueRed.png"));
        
        loadHeader()
                ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSeats = new javax.swing.ButtonGroup();
        nav = new javax.swing.JPanel();
        dropDown = new javax.swing.JLabel();
        accountTab = new javax.swing.JLabel();
        calculatorTab = new javax.swing.JLabel();
        seatsTab = new javax.swing.JLabel();
        ticketsTab = new javax.swing.JLabel();
        lblSelectedDiscount = new javax.swing.JLabel();
        lblCash = new javax.swing.JLabel();
        btnContinue = new javax.swing.JLabel();
        rCourtSide = new javax.swing.JRadioButton();
        rUpperBox = new javax.swing.JRadioButton();
        rLowerBox = new javax.swing.JRadioButton();
        rGeneralAdmission = new javax.swing.JRadioButton();
        bg = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setOpaque(false);
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dropdown/DropDown.png"))); // NOI18N
        dropDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav.add(dropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 38, -1, -1));

        accountTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dropdown/AccountBtnGray.png"))); // NOI18N
        accountTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav.add(accountTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        calculatorTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator/CalculatorBtnGray.png"))); // NOI18N
        nav.add(calculatorTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        seatsTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/SeatsBtnRed.png"))); // NOI18N
        nav.add(seatsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        ticketsTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/TICKETBTNgray.png"))); // NOI18N
        nav.add(ticketsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 270, 90));

        lblSelectedDiscount.setFont(new java.awt.Font("Futura Lt BT", 0, 18)); // NOI18N
        lblSelectedDiscount.setForeground(new java.awt.Color(255, 102, 102));
        lblSelectedDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectedDiscount.setText("Selected discount: none");
        add(lblSelectedDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 230, -1));

        lblCash.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblCash.setForeground(new java.awt.Color(204, 204, 204));
        lblCash.setText("0");
        add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 578, 80, 20));

        btnContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/ContinueBlack.png"))); // NOI18N
        btnContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnContinueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnContinueMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnContinueMouseReleased(evt);
            }
        });
        add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        buttonGroupSeats.add(rCourtSide);
        rCourtSide.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rCourtSide.setToolTipText("P500");
        rCourtSide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/RadioButtonNotSelected.png"))); // NOI18N
        rCourtSide.setOpaque(false);
        rCourtSide.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/RadioButtonSelected.png"))); // NOI18N
        add(rCourtSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 180, -1));

        buttonGroupSeats.add(rUpperBox);
        rUpperBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rUpperBox.setToolTipText("P350");
        rUpperBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/RadioButtonNotSelected.png"))); // NOI18N
        rUpperBox.setOpaque(false);
        rUpperBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/RadioButtonSelected.png"))); // NOI18N
        add(rUpperBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 295, 180, -1));

        buttonGroupSeats.add(rLowerBox);
        rLowerBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rLowerBox.setToolTipText("P300");
        rLowerBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/RadioButtonNotSelected.png"))); // NOI18N
        rLowerBox.setOpaque(false);
        rLowerBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/RadioButtonSelected.png"))); // NOI18N
        add(rLowerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 215, 190, -1));

        buttonGroupSeats.add(rGeneralAdmission);
        rGeneralAdmission.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rGeneralAdmission.setSelected(true);
        rGeneralAdmission.setToolTipText("P250");
        rGeneralAdmission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/RadioButtonNotSelected.png"))); // NOI18N
        rGeneralAdmission.setOpaque(false);
        rGeneralAdmission.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/RadioButtonSelected.png"))); // NOI18N
        add(rGeneralAdmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/Background.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseEntered
        btnContinue.setIcon(iconContinueH);
    }//GEN-LAST:event_btnContinueMouseEntered

    private void btnContinueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseExited
        btnContinue.setIcon(iconContinue);
    }//GEN-LAST:event_btnContinueMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //updates the cash everytime the component is shown
        lblCash.setText(String.valueOf(AppFrame.currentLoggedCash));
        lblSelectedDiscount.setVisible(false);
        
        prompt = new PromptDiscount();
    }//GEN-LAST:event_formComponentShown

    private void btnContinueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinueMouseReleased
        
    if (PromptDiscount.isDiscountAlreadySelected == false){

        if (!prompt.isVisible())
            prompt.setVisible(true);

    } else {
        
        if (rGeneralAdmission.isSelected()){
            //multiply to get discount value
            totalPayment = 250;
            seatChosed = "GENERAL ADMISSION";
        }
        else if (rLowerBox.isSelected()){
            totalPayment = 300;
            seatChosed = "LOWER BOX";
        }
        else if (rUpperBox.isSelected()){
            totalPayment = 350;
            seatChosed = "UPPER BOX";
        }
        else if (rCourtSide.isSelected()){
            totalPayment = 500;
            seatChosed = "COURT SIDE";
        }
        
        AppFrame.cardLayout.show(this.getParent(), "cardReceipt");
        PromptDiscount.isDiscountAlreadySelected = false;
    }
        
    }//GEN-LAST:event_btnContinueMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountTab;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnContinue;
    private javax.swing.ButtonGroup buttonGroupSeats;
    private javax.swing.JLabel calculatorTab;
    private javax.swing.JLabel dropDown;
    private javax.swing.JLabel lblCash;
    public static javax.swing.JLabel lblSelectedDiscount;
    private javax.swing.JPanel nav;
    private javax.swing.JRadioButton rCourtSide;
    private javax.swing.JRadioButton rGeneralAdmission;
    private javax.swing.JRadioButton rLowerBox;
    private javax.swing.JRadioButton rUpperBox;
    private javax.swing.JLabel seatsTab;
    private javax.swing.JLabel ticketsTab;
    // End of variables declaration//GEN-END:variables
private void loadHeader() {
        
        dropDown.setVisible(false);
        
        accountTab.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ImageIcon accountHovered = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnRed.png"));
                accountTab.setIcon(accountHovered);
            }
            @Override
            public void mouseExited(MouseEvent e) {
                ImageIcon accountExited = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnGray.png"));
                if (!dropDown.isVisible())
                    accountTab.setIcon(accountExited);
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                ImageIcon accountHovered = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnRed.png"));
                accountTab.setIcon(accountHovered);
                
                if (!dropDown.isVisible())
                    dropDown.setVisible(true);
                else
                    dropDown.setVisible(false);
            }
            
        });
        
        dropDown.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ImageIcon dropHistoryHovered = new ImageIcon(getClass().getResource("/images/dropdown/DropDownHistorySelect.png"));
                ImageIcon dropLogoutHovered = new ImageIcon(getClass().getResource("/images/dropdown/DropDownLogoutSelect.png"));

                dropDown.addMouseMotionListener(new MouseMotionAdapter() {
                    @Override
                    public void mouseMoved(MouseEvent e) {
                        if (e.getY() < 20) {
                            dropDown.setIcon(dropHistoryHovered);
                        } else {
                            dropDown.setIcon(dropLogoutHovered);
                        }
                    }

                });

            }

            @Override
            public void mouseExited(MouseEvent e) {

                ImageIcon dropExited = new ImageIcon(getClass().getResource("/images/dropdown/DropDown.png"));
                dropDown.setIcon(dropExited);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.getY() < 20) {
                    FrameHistory frameHistory = new FrameHistory();

                    frameHistory.setVisible(true);
                } else {
                    LoginFrame loginFrame = new LoginFrame();
                    loginFrame.setVisible(true);

                    JFrame thisFrame = (JFrame) SwingUtilities.getWindowAncestor(getComponent(0));
                    thisFrame.dispose();

                }

                dropDown.setVisible(false);
            }

        });

    }
}
