package pbaticketsales.MainApplication;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import pbaticketsales.LoginFrame;
import static pbaticketsales.MainApplication.AppFrame.currentLoggedID;
import pbaticketsales.db;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dewberry
 */
public class PanelReceipt extends javax.swing.JPanel {

    ImageIcon iconMabuhay, iconMabuhayH;
    Connection conn = null;

    public double totalPayment;
    public static double discountPrice = 0;
    public static double totalPrice = 0;
    public static double change = 0;
    public static String currentDate = "no date";

    /**
     * Creates new form PanelTickets
     */
    public PanelReceipt() {
        initComponents();
        conn = db.java_db();
        iconMabuhay = new ImageIcon(getClass().getResource("/images/receipt/MabuhayBtnBlack.png"));
        iconMabuhayH = new ImageIcon(getClass().getResource("/images/receipt/MabuhayBtnRed.png"));

        loadHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSeats = new javax.swing.ButtonGroup();
        nav = new javax.swing.JPanel();
        dropDown = new javax.swing.JLabel();
        accountTab = new javax.swing.JLabel();
        calculatorTab = new javax.swing.JLabel();
        seatsTab = new javax.swing.JLabel();
        ticketsTab = new javax.swing.JLabel();
        btnMabuhay = new javax.swing.JLabel();
        lblTicketBooked = new javax.swing.JLabel();
        fieldCash = new javax.swing.JLabel();
        fieldChange = new javax.swing.JLabel();
        fieldDiscountedPrice = new javax.swing.JLabel();
        fieldOrigPrice = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setOpaque(false);
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dropdown/DropDown.png"))); // NOI18N
        dropDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav.add(dropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 38, -1, -1));

        accountTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dropdown/AccountBtnGray.png"))); // NOI18N
        accountTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav.add(accountTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        calculatorTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator/CalculatorBtnGray.png"))); // NOI18N
        nav.add(calculatorTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        seatsTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seats/SeatsBtnGray.png"))); // NOI18N
        nav.add(seatsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        ticketsTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets/TICKETBTNgray.png"))); // NOI18N
        nav.add(ticketsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 270, 90));

        btnMabuhay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receipt/MabuhayBtnBlack.png"))); // NOI18N
        btnMabuhay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMabuhay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMabuhayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMabuhayMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMabuhayMouseReleased(evt);
            }
        });
        add(btnMabuhay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        lblTicketBooked.setFont(new java.awt.Font("Futura BdCn BT", 0, 18)); // NOI18N
        lblTicketBooked.setForeground(new java.awt.Color(204, 204, 204));
        lblTicketBooked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTicketBooked.setText("NONE");
        add(lblTicketBooked, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 280, 40));

        fieldCash.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        fieldCash.setForeground(new java.awt.Color(204, 204, 204));
        fieldCash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldCash.setText("0");
        add(fieldCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, 50));

        fieldChange.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        fieldChange.setForeground(new java.awt.Color(204, 204, 204));
        fieldChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldChange.setText("0");
        add(fieldChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 190, 40));

        fieldDiscountedPrice.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        fieldDiscountedPrice.setForeground(new java.awt.Color(204, 204, 204));
        fieldDiscountedPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldDiscountedPrice.setText("0");
        add(fieldDiscountedPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 190, 50));

        fieldOrigPrice.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        fieldOrigPrice.setForeground(new java.awt.Color(204, 204, 204));
        fieldOrigPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fieldOrigPrice.setText("0");
        add(fieldOrigPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receipt/background.jpg"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMabuhayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMabuhayMouseEntered
        btnMabuhay.setIcon(iconMabuhayH);
    }//GEN-LAST:event_btnMabuhayMouseEntered

    private void btnMabuhayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMabuhayMouseExited
        btnMabuhay.setIcon(iconMabuhay);
    }//GEN-LAST:event_btnMabuhayMouseExited

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //updates the prices everytime the component is shown
        double totalTax;
        double selectedSeatPrice;
        double cash;
        String ticketChoosen = "none";

        selectedSeatPrice = PanelSeats.totalPayment;
        cash = AppFrame.currentLoggedCash;

        totalTax = selectedSeatPrice;
        discountPrice = PromptDiscount.totalDiscount * totalTax;

        totalPrice = totalTax - discountPrice;
        change = cash - totalPrice;

        //for ticket choosen
        if (PanelTickets.ticketChosed == 1) {
            ticketChoosen = "TALK-N-TEXT vs GLOBALPORT";
        } else if (PanelTickets.ticketChosed == 2) {
            ticketChoosen = "SAN MIGUEL vs KIA SORENTO";
        } else if (PanelTickets.ticketChosed == 3) {
            ticketChoosen = "MERALCO vs ALASKA";
        } else if (PanelTickets.ticketChosed == 4) {
            ticketChoosen = "PHOENIX vs NLEX";
        }

        //TIME TO UPDATE FILEDS
        fieldOrigPrice.setText(String.valueOf(totalTax));
        fieldDiscountedPrice.setText(String.valueOf(totalPrice));

        fieldCash.setText(String.valueOf(cash));
        fieldChange.setText(String.valueOf(change));

        lblTicketBooked.setText(ticketChoosen);

    }//GEN-LAST:event_formComponentShown

    private void btnMabuhayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMabuhayMouseReleased
        // if change is not less than 0, then proceed
        if (change >= 0) {
            String pastHistory = getPastHistory();

            //for ticket choosen
            String ticketChoosen = "none";
            if (PanelTickets.ticketChosed == 1) {
                ticketChoosen = "TALK-N-TEXT vs GLOBALPORT";
            } else if (PanelTickets.ticketChosed == 2) {
                ticketChoosen = "SAN MIGUEL vs KIA SORENTO";
            } else if (PanelTickets.ticketChosed == 3) {
                ticketChoosen = "MERALCO vs ALASKA";
            } else if (PanelTickets.ticketChosed == 4) {
                ticketChoosen = "PHOENIX vs NLEX";
            }

            //fo user history
            //for date
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            currentDate = dtf.format(now);

            String entryHistory = "\n\n----------" + currentDate + "----------" + "\n" + ticketChoosen + "\n - Seat Price: " + PanelSeats.totalPayment
                    + "\n - Discount: " + PromptDiscount.totalDiscount + pastHistory;

            String sql = "update Users set cash = ?, history = ? where id = ?";
            PreparedStatement pst;

            try {
                pst = conn.prepareStatement(sql);
                pst.setDouble(1, change);
                pst.setString(2, entryHistory);
                pst.setInt(3, AppFrame.currentLoggedID);
                pst.executeUpdate();
                conn.close();
                pst.close();

            } catch (SQLException ex) {
                Logger.getLogger(PanelReceipt.class.getName()).log(Level.SEVERE, null, ex);
            }

            FrameReceipt frameReceipt = new FrameReceipt();
            
            frameReceipt.setLocation(this.getLocationOnScreen().x - 345, this.getLocationOnScreen().y - 50);
            frameReceipt.setVisible(true);

            AppFrame.cardLayout.show(this.getParent(), "cardCalculator");
        }
        
        //else, add some money first
        else {
            JOptionPane.showMessageDialog(this, "Oops! Your money is insufficient. Add some money first!");
            AppFrame.cardLayout.show(this.getParent(), "cardTransaction");
        }


    }//GEN-LAST:event_btnMabuhayMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountTab;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnMabuhay;
    private javax.swing.ButtonGroup buttonGroupSeats;
    private javax.swing.JLabel calculatorTab;
    private javax.swing.JLabel dropDown;
    private javax.swing.JLabel fieldCash;
    private javax.swing.JLabel fieldChange;
    private javax.swing.JLabel fieldDiscountedPrice;
    private javax.swing.JLabel fieldOrigPrice;
    private javax.swing.JLabel lblTicketBooked;
    private javax.swing.JPanel nav;
    private javax.swing.JLabel seatsTab;
    private javax.swing.JLabel ticketsTab;
    // End of variables declaration//GEN-END:variables

    private String getPastHistory() {
        ResultSet rs = null;
        String sql = "Select history from Users where id = ?";
        PreparedStatement pst;
        String info = "";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, AppFrame.currentLoggedID);
            rs = pst.executeQuery();

            info = rs.getString("history");

        } catch (SQLException ex) {
            Logger.getLogger(PanelReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }

        return info;

    }

    private void loadHeader() {

        dropDown.setVisible(false);

        accountTab.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ImageIcon accountHovered = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnRed.png"));
                accountTab.setIcon(accountHovered);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                ImageIcon accountExited = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnGray.png"));
                if (!dropDown.isVisible()) {
                    accountTab.setIcon(accountExited);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                ImageIcon accountHovered = new ImageIcon(getClass().getResource("/images/dropdown/AccountBtnRed.png"));
                accountTab.setIcon(accountHovered);

                if (!dropDown.isVisible()) {
                    dropDown.setVisible(true);
                } else {
                    dropDown.setVisible(false);
                }
            }

        });

        dropDown.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                ImageIcon dropHistoryHovered = new ImageIcon(getClass().getResource("/images/dropdown/DropDownHistorySelect.png"));
                ImageIcon dropLogoutHovered = new ImageIcon(getClass().getResource("/images/dropdown/DropDownLogoutSelect.png"));

                dropDown.addMouseMotionListener(new MouseMotionAdapter() {
                    @Override
                    public void mouseMoved(MouseEvent e) {
                        if (e.getY() < 20) {
                            dropDown.setIcon(dropHistoryHovered);
                        } else {
                            dropDown.setIcon(dropLogoutHovered);
                        }
                    }

                });

            }

            @Override
            public void mouseExited(MouseEvent e) {

                ImageIcon dropExited = new ImageIcon(getClass().getResource("/images/dropdown/DropDown.png"));
                dropDown.setIcon(dropExited);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.getY() < 20) {
                    FrameHistory frameHistory = new FrameHistory();

                    frameHistory.setVisible(true);
                } else {
                    LoginFrame loginFrame = new LoginFrame();
                    loginFrame.setVisible(true);

                    JFrame thisFrame = (JFrame) SwingUtilities.getWindowAncestor(getComponent(0));
                    thisFrame.dispose();

                }

                dropDown.setVisible(false);
            }

        });

    }
}
